fix: error stack traces in transpiled TypeScript (#740)
* fix: error stack traces in transpiled TypeScript

Example code:

```ts
interface User {
  name: string;
  email: string;
}

const err: Error = new Error("boom!"); throw err;
```

Deno output:

```
error: Uncaught (in promise) Error: boom!
const err: Error = new Error("boom!"); throw err;
                   ^
    at file:///project/x.ts:6:20

Zinnia before this change - notice the missing `: Error` text
and wrong source code line & column numbers:

```
error: Uncaught (in promise) Error: boom!
const err = new Error("boom!");
            ^
    at file:///project/x.ts:1:13
```

Zinnia after this change (same output as from Deno):

```
error: Uncaught (in promise) Error: boom!
const err: Error = new Error("boom!"); throw err;
                   ^
    at file:///project/x.ts:6:20
```

---------

Signed-off-by: Miroslav Bajtoš <oss@bajtos.net>